config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  post 's' => 'top#search'
  get 's/:tags' => 'top#result'
  resources :posts
  get 'tags' => 'tags#index'
  post 'tags' => 'tags#create'
  get 'tags/:id' => 'tags#destroy'

  devise_for :users, skip: :all
  devise_scope :user do
  get 'login' => 'devise/sessions#new', as: :new_user_session
  post 'login' => 'devise/sessions#create', as: :user_session
  delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
  get 'signup' => 'devise/registrations#new', as: :new_user_registration
  post 'signup' => 'devise/registrations#create', as: :user_registration
  get 'signup/cancel' => 'devise/registrations#cancel', as: :cancel_user_registration
  get 'user' => 'devise/registrations#edit', as: :edit_user_registration
  patch 'user' => 'devise/registrations#update', as: nil
  put 'user' => 'devise/registrations#update', as: :update_user_registration
  delete 'user' => 'devise/registrations#destroy', as: :destroy_user_registration
  get 'password' => 'devise/passwords#new', as: :new_user_password
  post 'password' => 'devise/passwords#create', as: :user_password
  get 'password/edit' => 'devise/passwords#edit', as: :edit_user_password
  patch 'password' => 'devise/passwords#update'
  put 'password' => 'devise/passwords#update', as: :update_user_password
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    redirect_to '/'
  end

  # GET /posts/1 or /posts/1.json
  def show
    redirect_to edit_post_path(set_post)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    tags = PostTag.where(post_id: @post.id)
    tags_list_str = []
    for tag in tags do
      tag_str = Tag.find(tag.tag_id)
      tags_list_str.push(tag_str.name)
    end
    @tags_str = tags_list_str.join(',')
    #puts tag_str.name

  end

  # POST /posts or /posts.json
  def create
    upload_file = params[:post][:file]
    if upload_file.present?
      upload_file_name = random_string(20)+upload_file.original_filename
      upload_dir = Rails.root.join("public", "user_file")
      upload_file_path = upload_dir + upload_file_name
      db_upload_file_path = "/user_file/" + upload_file_name
      File.binwrite(upload_file_path, upload_file.read)
    end

    @post = Post.new(name: params[:post][:name], path: db_upload_file_path, user_id: current_user.id)

    tags_str = params[:post][:tag]
    tags_list_str = tags_str.split(',')



    respond_to do |format|
      if @post.save
        for tag_str in tags_list_str do
          tag = Tag.find_by(name:tag_str)
          @post_tag = PostTag.new(post_id: @post.id, tag_id: tag.id)
          @post_tag.save
        end
        format.html { redirect_to '/', notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to '/', notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to '/', notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name, :path, :user_id)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tag = Tag.new
    @tags = Tag.where(user_id:current_user.id).order(created_at: :desc)
  end

  def create
    @tag = current_user.tags.build(tag_params)
    if @tag.save
      redirect_to tags_path, notice: "タグを追加しました"
    else
      render :new
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to tags_path, notice: "タグを削除しました"
  end

  private
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    if user_signed_in?
      @posts = Post.where(user_id:current_user.id).order(created_at: :desc)
    else
      redirect_to  '/login'
    end
  end

  def search
    tags_str = params[:tags]
    
  end

  def result
    tags_str = params[:tags]
    @posts = []
    p tags_str
    tags_list_str = tags_str.split('+')
    for tag_str in tags_list_str do
      tag = Tag.find_by(name:tag_str)
      post_ids = PostTag.where(tag_id:tag.id)
      for post in post_ids do
        @posts.push(Post.find(post.post_id))
      end
    end

    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def random_string(n)
    chars = ("0".."9").to_a.join + ("A".."Z").to_a.join + ("a".."z").to_a.join
    (Array.new(n).map! {|e| chars[rand(chars.length)]}).join
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tagkan</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel ="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  </head>

  <body>
    <!--<main class="container mx-auto mt-28 px-5 flex">-->
      <%= yield %>
    <!--</main>-->
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, class: "contents") do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <p>ファイル名</p>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <p>ファイル選択</p>
    <%= form.file_field :file %>

  </div>

  <div class="my-5">
      <p>タグを追加</p>
      <%= form.text_field :tag, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit "アップロード", class: "inline-block bg-indigo-500 hover:bg-indigo-600 active:bg-indigo-700 focus-visible:ring ring-indigo-300 text-white text-sm md:text-base font-semibold text-center rounded-lg outline-none transition duration-100 px-8 py-3" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= post.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Path:</strong>
    <img src="<%= post.path %>">
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= post.user_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this post", post, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this post', edit_post_path(post), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/posts/edit.html.erb
<main class="container mx-auto mt-28 px-5 flex">
<div class="mx-auto md:w-2/3 w-full">
  <a href="/"><i class="mb-5 fas fa-chevron-left"> 戻る</i></a>
  <h1 class="font-bold text-4xl">編集</h1>

  <%= form_with(model: @post, class: "contents") do |form| %>
    <% if @post.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% @post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="my-5">
      <p>ファイル名</p>
      <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>


    <div class="my-5">
        <p>タグを編集</p>
        <%= form.text_field :tag, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", value: @tags_str %>
    </div>

    <div class="my-10">
      <a href="<%= @post.path %>" class="hidden lg:inline-block bg-gray-200 hover:bg-gray-300 focus-visible:ring ring-indigo-300 text-gray-500 active:text-gray-700 text-sm md:text-base font-semibold text-center rounded-lg outline-none transition duration-100 px-4 py-3" download="<%= @post.name %>">
        <i class="fas fa-download">ファイルをダウンロード</i>
      </a>

    </div>

    <div class="inline">
      <%= form.submit "更新", class: "inline-block bg-indigo-500 hover:bg-indigo-600 active:bg-indigo-700 focus-visible:ring ring-indigo-300 text-white text-sm md:text-base font-semibold text-center rounded-lg outline-none transition duration-100 px-8 py-3" %>
    </div>
  <% end %>
  <%= link_to '削除', post_path(@post), data: {"turbo-method": :delete}, class: "hidden lg:inline-block bg-gray-200 hover:bg-gray-300 focus-visible:ring ring-indigo-300 text-gray-500 active:text-gray-700 text-sm md:text-base font-semibold text-center rounded-lg outline-none transition duration-100 px-8 py-3 mx-3" %>
</div>
</main>

app/views/posts/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Posts</h1>
    <%= link_to 'New post', new_post_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="posts" class="min-w-full">
    <%= render @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<main class="container mx-auto mt-28 px-5 flex">
<div class="mx-auto md:w-2/3 w-full">
  <a href="/"><i class="mb-5 fas fa-chevron-left"> 戻る</i></a>

  <h1 class="font-bold text-4xl">ファイル追加</h1>


  <%= form_with(model: @post, class: "contents") do |form| %>
    <% if @post.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% @post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="my-5">
      <p>ファイル名</p>
      <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <p>ファイル選択</p>
      <%= form.file_field :file %>

    </div>

    <div class="my-5">
        <p>タグを追加</p>
        <%= form.text_field :tag, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="inline">
      <%= form.submit "アップロード", class: "inline-block bg-indigo-500 hover:bg-indigo-600 active:bg-indigo-700 focus-visible:ring ring-indigo-300 text-white text-sm md:text-base font-semibold text-center rounded-lg outline-none transition duration-100 px-8 py-3" %>
    </div>
  <% end %>
</div>
</main>

app/views/posts/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @post %>

    <%= link_to 'Edit this post', edit_post_path(@post), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this post', post_path(@post), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to posts', posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/tags/index.html.erb
<main class="container mx-auto mt-28 px-5 flex">
<div class="mx-auto md:w-2/3 w-full">
  <a href="/"><i class="mb-5 fas fa-chevron-left"> 戻る</i></a>

  <h1 class="font-bold text-4xl">タグ管理</h1>

  <div class="bg-white py-6 sm:py-8 lg:py-12">

  <div class="max-w-screen-2xl px-4 md:px-8 mx-auto">
    <!-- text - start -->
<div class="mb-10 md:mb-16">

  <%= form_with(model: @tag, class: "w-full max-w-md flex gap-2 mx-auto") do |form| %>
    <%= form.text_field :name, class: "w-full flex-1 bg-gray-white text-gray-800 placeholder-gray-400 border border-gray-300 focus:ring ring-indigo-300 rounded outline-none transition duration-100 px-3 py-2" ,placeholder: "タグを追加"%>

    <%= button_tag type: "submit", class: "inline-block bg-indigo-500 hover:bg-indigo-600 active:bg-indigo-700 focus-visible:ring ring-indigo-300 text-white text-sm md:text-base font-semibold text-center rounded outline-none transition duration-100 px-4 py-2" do %>
     <i class="fas fa-plus"></i>
     <% end %>
  <% end %>
</div>
<!-- text - end -->
    <div class="grid sm:grid-cols-2 xl:grid-cols-3 gap-4 md:gap-8">
      <% @tags.each do |tag| %>

      <!-- feature - start -->
      <div class="flex bg-gray-50 border rounded-lg divide-x">

        <div class="flex items-center text-indigo-500 p-2 md:p-4 hover:bg-gray-300 transition">
          <a href="/tags/<%= tag.id %>" data-method="delete">
          <i class="fas fa-times"></i>
          </a>
        </div>
        <div class="flex items-center text-indigo-500 p-2 md:p-4 hover:bg-gray-300 transition">
          <i class="fas fa-pen"></i>
        </div>
        <div class="p-4 md:p-6">
          <h3 class="text-lg md:text-xl font-semibold"><%= tag.name %></h3>

        </div>

      </div>
      <!-- feature - end -->
      <% end %>

    </div>
  </div>
</div>


</div>
</main>

app/views/top/index.html.erb
<!--
CSSはtailwindを使用（https://tailwindui.com/）
tailwindのテンプレートをflowriftからダウンロードして使用(https://flowrift.com/)
-->
<div class="bg-white lg:pb-12">
  <div class="max-w-screen-2xl px-4 md:px-8 mx-auto">
    <header class="flex justify-between items-center py-4 md:py-8">
      <!-- logo - start -->
      <a href="/" class="inline-flex items-center text-black-800 text-2xl md:text-3xl font-bold gap-2.5" aria-label="logo">
        #タグカン
      </a>
      <!-- logo - end -->
      <!--<form class="w-full max-w-md flex gap-2">
        <input placeholder="タグを入力" class="w-full flex-1 bg-gray-white text-gray-800 placeholder-gray-400 border border-gray-300 focus:ring ring-indigo-300 rounded outline-none transition duration-100 px-3 py-2" />

        <button class="inline-block bg-indigo-500 hover:bg-indigo-600 active:bg-indigo-700 focus-visible:ring ring-indigo-300 text-white text-sm md:text-base font-semibold text-center rounded outline-none transition duration-100 px-4 py-2"><i class="fas fa-search"></i></button>
      </form>-->

      <%= form_with(url: '/s', class: "w-full max-w-md flex gap-2 mx-auto") do |form| %>
        <%= form.text_field :tags, class: "w-full flex-1 bg-gray-white text-gray-800 placeholder-gray-400 border border-gray-300 focus:ring ring-indigo-300 rounded outline-none transition duration-100 px-3 py-2" ,placeholder: "タグを追加"%>

        <%= button_tag type: "submit", class: "inline-block bg-indigo-500 hover:bg-indigo-600 active:bg-indigo-700 focus-visible:ring ring-indigo-300 text-white text-sm md:text-base font-semibold text-center rounded outline-none transition duration-100 px-4 py-2" do %>
         <i class="fas fa-search"></i>
         <% end %>
      <% end %>

      <!-- buttons - start -->
      <% if user_signed_in? %>
      <div class="hidden lg:flex flex-col sm:flex-row sm:justify-center lg:justify-start gap-2.5 -ml-8">
        <%= link_to 'タグを管理', tags_path, class: "hidden lg:inline-block bg-gray-200 hover:bg-gray-300 focus-visible:ring ring-indigo-300 text-gray-500 active:text-gray-700 text-sm md:text-base font-semibold text-center rounded-lg outline-none transition duration-100 px-8 py-3" %>
        <%= link_to 'ファイルを追加', new_post_path, class: "inline-block bg-indigo-500 hover:bg-indigo-600 active:bg-indigo-700 focus-visible:ring ring-indigo-300 text-white text-sm md:text-base font-semibold text-center rounded-lg outline-none transition duration-100 px-8 py-3" %>
        <%= link_to "ログアウト", destroy_user_session_path, data: {"turbo-method": :delete}, class: "inline-block focus-visible:ring ring-indigo-300 text-gray-500 hover:text-indigo-500 active:text-indigo-600 text-sm md:text-base font-semibold text-center rounded-lg outline-none transition duration-100 px-4 py-3" %>
      </div>
      <% else %>
      <div class="hidden lg:flex flex-col sm:flex-row sm:justify-center lg:justify-start gap-2.5 -ml-8">
        <%= link_to "ログイン", new_user_session_path, class: "inline-block focus-visible:ring ring-indigo-300 text-gray-500 hover:text-indigo-500 active:text-indigo-600 text-sm md:text-base font-semibold text-center rounded-lg outline-none transition duration-100 px-4 py-3" %>
        <%= link_to "新規登録", new_user_registration_path, class: "inline-block bg-indigo-500 hover:bg-indigo-600 active:bg-indigo-700 focus-visible:ring ring-indigo-300 text-white text-sm md:text-base font-semibold text-center rounded-lg outline-none transition duration-100 px-8 py-3" %>
      </div>
      <% end %>
      <!-- buttons - end -->
    </header>

    <hr>
    <div>
      <% @posts.each do |post| %>
      <div class="bg-white py-5 sm:py-5 lg:py-5 w-full">
      <div class="max-w-screen-2xl px-4 md:px-8 mx-auto">
        <div class="flex flex-col sm:flex-row justify-between items-center bg-gray-100 rounded-lg gap-4 p-4 md:p-8">
          <div>
            <h2 class="text-indigo-500 text-xl md:text-2xl font-bold"><a href="<%= edit_post_path(post) %>"><%= post.name %></a></h2>
            <p class="text-gray-600">
              <% post.post_tags.each do |tag| %>
              <% tag = Tag.find(tag.tag_id) %>
              <a href="/s/<%= tag.name %>">#<%= tag.name %></a>
              <% end %>
            </p>
          </div>


          <a href="<%= post.path %>" class="hidden lg:inline-block bg-gray-200 hover:bg-gray-300 focus-visible:ring ring-indigo-300 text-gray-500 active:text-gray-700 text-sm md:text-base font-semibold text-center rounded-lg outline-none transition duration-100 px-4 py-3" download="<%= post.name %>">
            <i class="fas fa-download"></i>
          </a>

        </div>
      </div>
    </div>
      <% end %>


    </div>

  </div>
</div>